os: linux

language: node_js

node_js:
  - lts/*

services:
  - docker

before_install:
  - docker build -t uanoob/web-app -f Dockerfile.dev .

script:
  - docker run -e CI=true uanoob/web-app npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: '$AWS_ACCESS_KEY'
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
  region: 'eu-central-1'
  app: 'web-app'
  env: 'WebApp-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-775403175877'
  bucket_path: 'web-app'
  on:
    branch: master
