version: '3'

services:
  react-app:
    restart: always
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
  tests:
    restart: always
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ['npm', 'run', 'test']
